package com.chen.firstdemo.greendao_demo.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.chen.firstdemo.greendao_demo.entry.ClassroomDomain;
import com.chen.firstdemo.greendao_demo.entry.UserDomain;

import com.chen.firstdemo.greendao_demo.dao.ClassroomDomainDao;
import com.chen.firstdemo.greendao_demo.dao.UserDomainDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig classroomDomainDaoConfig;
    private final DaoConfig userDomainDaoConfig;

    private final ClassroomDomainDao classroomDomainDao;
    private final UserDomainDao userDomainDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        classroomDomainDaoConfig = daoConfigMap.get(ClassroomDomainDao.class).clone();
        classroomDomainDaoConfig.initIdentityScope(type);

        userDomainDaoConfig = daoConfigMap.get(UserDomainDao.class).clone();
        userDomainDaoConfig.initIdentityScope(type);

        classroomDomainDao = new ClassroomDomainDao(classroomDomainDaoConfig, this);
        userDomainDao = new UserDomainDao(userDomainDaoConfig, this);

        registerDao(ClassroomDomain.class, classroomDomainDao);
        registerDao(UserDomain.class, userDomainDao);
    }
    
    public void clear() {
        classroomDomainDaoConfig.clearIdentityScope();
        userDomainDaoConfig.clearIdentityScope();
    }

    public ClassroomDomainDao getClassroomDomainDao() {
        return classroomDomainDao;
    }

    public UserDomainDao getUserDomainDao() {
        return userDomainDao;
    }

}
